allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - prisma
patchedDependencies:
  '@uiw/react-md-editor@4.1.0': patches/@uiw__react-md-editor@4.1.0.patch
